### ISSUE TITLE
Impossible lap times when lapping CPU

### ISSUE THREAD

**Issue by atsymboldot** [agateau/pixelwheels#106]
Version 0.19.0, played on Android 10 on a moto g7 play

If you complete a race after lapping the CPUs, their fastest lap time is often slower than [total time] / 3. This shouldn't be possible.

In the attached screenshot, for example, I lapped the CPUs in position 3 through 6, but not 2.

2. Police (best 12.962, total 45.597; 12.962 * 3 = 38.886 < 45.597, good)
3. Red (best 18.432, total 49.958; 18.432 * 3 = 55.296 > 49.958, impossible)
4. Rocket (best 19.032, total 54.404; 19.032 * 3 = 57.096 > 54.404, impossible)
5. 2-Deuch (best 24.165, total 1:10.536; 24.165 * 3 = 1:12.495 > 1:10.536, impossible)
6. Dark M (best 24.016, total 1:10.616; 24.016 * 3 = 1:12.048 > 1:10.616, impossible)

![2021-03-05 pixelwheels lapping](https://user-images.githubusercontent.com/32006849/110155246-33a7c280-7d9a-11eb-93ed-bb22a0e97865.png)

Maybe a reasonable solution is to replace the best lap calculation at the end of `LapPositionComponent::markRaceFinished` to something like:

    float avgLapTime = mTotalTime / mTrack.getTotalLapCount();
    mBestLapTime = hasBestLapTime() ? Math.min(mBestLapTime, avgLapTime) : avgLapTime;

**Comment by agateau** [comment]
Good catch! Going to look into this. Thanks for the report!
