### ISSUE TITLE
Fails to build on F-Droid

### ISSUE THREAD

**Issue by jspricke** [agateau/pixelwheels#113]
Hi,

the latest version (0.19.1) fails to build on F-Droid:
```
2021-04-22 12:27:11,848 ERROR: Could not build app com.agateau.tinywheels.android: glob path 'tools/packr.jar' did not match any files/dirs
```
https://monitor.f-droid.org/builds/log/com.agateau.tinywheels.android/20

Would be great if you could help us fix it.

**Comment by agateau** [comment]
I think that's because I removed the bundled packr.jar file which F-Droid used to remove. If this is the problem then you just need to remove these lines: https://gitlab.com/agateau/fdroiddata/-/blob/master/metadata/com.agateau.tinywheels.android.yml#L28-29

**Comment by jspricke** [comment]
Done, thx! https://gitlab.com/fdroid/fdroiddata/-/commit/04c3b95d3f18aeb31b359450398912043a893259

**Comment by agateau** [comment]
Great!
