### ISSUE TITLE
Championship finish button doesn't work on Android

### ISSUE THREAD

**Issue by Eiim** [agateau/pixelwheels#119]
When attempting to press the finish button at the end of the championship, it doesn't return to the main menu. I can still return by pressing Android's back button.

I am using a Moto G7 Power with Android 10.

**Comment by agateau** [comment]
That is strange, is this with 0.19.1?

**Comment by Eiim** [comment]
Yes, with the F-Droid build. I think it might have worked when I first installed it a week or so ago, but it hasn't for a few days at least.

**Comment by agateau** [comment]
Very odd, will look into it.

**Comment by agateau** [comment]
Hi, I tried again to reproduce that bug but could not. Just to be sure there is no misunderstanding, we are talking about the button with the right arrow in the bottom-right corner of these screens? Does it fail for both?

![image](https://user-images.githubusercontent.com/3575/122876489-de39f600-d335-11eb-8ec3-c09d4be0dfac.png)

![image](https://user-images.githubusercontent.com/3575/122876602-fe69b500-d335-11eb-81d3-8d02301b233c.png)

**Comment by Eiim** [comment]
Yep, specifically the second image, I don't think I've had the issue with the first screen. I just went to reproduce it and it worked once the animations had finished, but I'm pretty sure it wasn't working at all before. I'll dig into it some more. Could be something strange with my phone specifically.

**Comment by agateau** [comment]
I received a message from another player with a similar issue, and he suggested this might be an issue with the display resolution being wider than expected (Pixel Wheels native ratio is 16:9), is your device very wide?

**Comment by Eiim** [comment]
Yes, I believe my phone is 1520x720, with a notch (which Pixel Wheels does not occupy).

**Comment by agateau** [comment]
I was able to reproduce and fix it! Can you try https://agateau.com/tmp/pixelwheels-itchio-0.21.0-alpha.2.apk and confirm it's fixed?

**Comment by Eiim** [comment]
Yes, that build works!

**Comment by agateau** [comment]
Great!
