### ISSUE TITLE
Shall I contribute Linux Desktop support?

### ISSUE THREAD

**Issue by samrocketman** [agateau/pixelwheels#125]
I just got the game from itch.  I noticed the Linux x64 download had no desktop integration so I made it for myself follow [freedesktop.org][1] guidelines.

[1]: https://www.freedesktop.org/

# Question

Would you like me to contribute my fix for desktop support?  I can contribute the `pixelwheels.desktop` file into your source tree.

# In your source code

I found [`DesktopLauncher.java`][2] so maybe it's partially supported?

[2]: https://github.com/agateau/pixelwheels/blob/4aaf2b3af0ea10aeb9745ee2a35d52878f7f0b9c/desktop/src/com/agateau/pixelwheels/desktop/DesktopLauncher.java

# My personal fix

```bash
sudo mkdir -p /usr/local/share/applications/ /usr/local/share/pixmaps/
sudo curl -fLo /usr/local/share/pixmaps/pixelwheels.png https://img.itch.zone/aW1nLzM5MTE4OTcucG5n/315x250%23c/0jHsNe.png
sudo tee /usr/local/share/applications/pixelwheels.desktop <<'EOF'
[Desktop Entry]
Type=Application
Version=0.20.0
Name=Pixel Wheels
GenericName=Racing game
GenericName[de]=Rennspiel
GenericName[es]=Juego de carreras
GenericName[fr_FR]=Jeu de course
Icon=pixelwheels.png
Exec=pixelwheels
Categories=Game;SportsGame;ArcadeGame;
EOF
```
And I symlinked `/usr/local/bin/pixelwheels`.

# Screenshot of desktop integration

![Screenshot from 2021-07-03 13-10-35](https://user-images.githubusercontent.com/875669/124361953-1ed02400-dc00-11eb-81b2-686a44bb9d14.png)

On Pop! OS 18.04.

**Comment by agateau** [comment]
I like the idea!

A few things to point out:
- DesktopLauncher.java is not related to creating a .desktop file, it is the "main()" function of the game
- The version field of a desktop file is the version of the Desktop Entry Specification that the .desktop file conforms too, so I don't think we should put the game version in there (see https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys)

Would be lovely if you couId open a PR to do the following:
- create tools/installer-data/linux directory and put the .desktop in it
- modify tools/create-archives to copy this tools/installer-data/linux directory to the Linux archive
- add a "create-launcher" script in this directory which would install the .desktop using `xdg-install-icon`

Let me know if you need any help with this.
