### ISSUE TITLE
Allow use of 'wasd' keys

### ISSUE THREAD

**Issue by WeebNetsu** [agateau/pixelwheels#129]
Hello!

I love the game, but currently it doesn't have wasd (or asd) support that I could see... This would be a great feature since it is much easier to press the wasd keys correctly than the arrow keys.

**Comment by agateau** [comment]
Hi, I think I can make the key bindings configurable, allowing for different configuration, since wasd is not optimal for all keyboard layouts.

**Comment by WeebNetsu** [comment]
> Hi, I think I can make the key bindings configurable, allowing for different configuration, since wasd is not optimal for all keyboard layouts.

That sounds great! Thanks :)
