### ISSUE TITLE
Bad performance on Redmi, Android 10

### ISSUE THREAD

**Issue by WeebNetsu** [agateau/pixelwheels#130]
I recently got a new phone, a Xiaomi Redmi 9C. Whilst most games generally play better on this device than on my previous device, this game in particular is very slow, with sometimes getting fps as low as 10... Could this be a problem with the game or maybe the device?

**Comment by agateau** [comment]
That is odd indeed. I am planning to spend some time profiling and optimizing the rendering, hopefully that will help.

**Comment by agateau** [comment]
Can I ask you to do the following? Would be super helpful:

- Go to "Settings > Misc > Developer Options > Debug"
- Enable "Show debug hud"
- Take a screenshot while playing
- Post the screenshot here

**Comment by WeebNetsu** [comment]
Here you go
I also took a screen recording if you want to see more details, [here](https://youtu.be/fhAdMsTz7_0).
![Screenshot_2021-08-06-17-46-22-396_com agateau tinywheels android](https://user-images.githubusercontent.com/52031254/128538390-3ea473ec-9488-4023-a9b0-fbb74767bf17.jpg)

**Comment by agateau** [comment]
Thanks! Will look into this.

**Comment by agateau** [comment]
Oups CI does not build apk yet (that's #105). I just uploaded a new build here in the mean time: https://agateau.com/tmp/pixelwheels-itchio-0.21.0-alpha.3.apk.

**Comment by WeebNetsu** [comment]
So I tried it, but nothing to report unfortunately, I'm still seeing the same results

**Comment by agateau** [comment]
Ah too bad :(. Just to eliminate possible suspects, can you try with music and sound effects off?

If it's not too much to ask, can you also try older builds from https://agateau.com/storage/pixelwheels/? If an older build is faster and you can narrow down which build started to get slow that would help a ton to decide where to investigate.

**Comment by WeebNetsu** [comment]
I think we found the problem! When the SFX is disabled then the game plays as smooth as butter!

**Comment by agateau** [comment]
That's good news, the investigation field just got much narrower :) Just to confirm: only SFX affects the performances, not music?

**Comment by WeebNetsu** [comment]
Yes, I played it with one enabled and the other disabled and then once more with both disabled and enabled, the fps drop was only there whenever the sfx was enabled :)

**Comment by agateau** [comment]
I am trying to narrow the scope even more. I suspect the performance issue is caused by the vehicle engine sounds. I created a build without these sounds, can you try it and tell me if performance is better: https://agateau.com/tmp/pixelwheels-itchio-0.21.0-alpha.4-noengine-sound.apk?

**Comment by WeebNetsu** [comment]
I tried it out, it was better, I still received  a bit of lag, but not nearly as much as before

I also noticed, whenever a car gets bumped the game lags a bit

**Comment by agateau** [comment]
Is your device running Android 10? The libgdx developers found a performance bug regarding sound in Android 10: https://github.com/libgdx/libgdx/issues/5786. It might be the same issue.

**Comment by WeebNetsu** [comment]
It may be :'((

**Comment by agateau** [comment]
I am going to try to implement the workaround mentioned in the libgdx issue: there are too many Android 10 installations to ignore that bug.

**Comment by agateau** [comment]
Can you try this apk https://agateau.com/tmp/pixelwheels-itchio-0.21.0-alpha.5.apk ? Hopefully it fixes your problem.

**Comment by WeebNetsu** [comment]
It's as smooth as butter!! With SFX turned on and all! Thank you so much :D

**Comment by agateau** [comment]
Great news! Thanks for all the testing!
