### ISSUE TITLE
Medals don't properly take into account CPU times

### ISSUE THREAD

**Issue by Eiim** [agateau/pixelwheels#131]
When showing medals on ending screens, if you still have CPU times on the leaderboard but didn't beat them, you will still get the medal as if only your times were on the leaderboard.

Example (slower in total time than all CPUs but still showed silver medal):
![image](https://user-images.githubusercontent.com/24627058/132250324-07b1845a-3d46-4c23-a72b-a306b0b177ed.png)

Actual leaderboard did not replace the CPU time with the new worse time:
![image](https://user-images.githubusercontent.com/24627058/132250391-eaa137d8-c04a-4cd8-97b6-f02a5cde3ebc.png)

**Comment by agateau** [comment]
Good catch!

**Comment by agateau** [comment]
Oups, I used the wrong bug number in commit message. Reopening.
