### ISSUE TITLE
"Broke a record" is not actually breaking a record

### ISSUE THREAD

**Issue by OliverLew** [agateau/pixelwheels#139]
The message appears as long as the result gets into the top 3. But "breaking a record" is getting the highest score.

**Comment by agateau** [comment]
Hi, sorry for the late answer. You are right the term is not accurate. What do you think would be better?

**Comment by OliverLew** [comment]
Not sure either. Maybe someone else knows the better phrasing.

**Comment by Sgt-Miller** [comment]
What about podium finish?
> In some individual sports, "podiums" is an official statistic, referring to the number of top three results an athlete has achieved over the course of a season or career.
https://en.wikipedia.org/wiki/Podium

**Comment by FabianPaci** [comment]
I actually think that 'breaking a record' fits well. I take it as you broke our third record, or second, or third. this is because of the 'a' as in 'any'.

**Comment by OliverLew** [comment]
> I take it as you broke our third record, or second, or third. this is because of the 'a' as in 'any'.

That "a" is referring to the number, i.e., how many top-3 of "best lap" or "total time" did you rank. As a result, the number is either 1 or 2. If you ranked top 3 in both, you get "You broke 2 records". So, 'a record' is not any of the top 3, but any of the two types of "records".

Of course, I am not a native speaker, you're more qualified to say the word "record" works this way :)

**Comment by FabianPaci** [comment]
I'm a native speaker but you are correct, my vocabulary is just trash.

**Comment by agateau** [comment]
This is a tricky one. I like the idea of saying something about entering the podium, but I am not sure how to word this.

**Comment by Zireael07** [comment]
@agateau: "Achieved a podium finish" or "got a podium finish" would be best imho (English major, but not native speaker here)

**Comment by OliverLew** [comment]
Phrasing based on "podium" is close in accuracy, but probably two concerns (from a non-native speaker's view): 1. Is the word "podium" common enough among native English speakers? 2. Ambiguity, will "podium finish" be interpreted only as top-3 among players in a single game rather than top-3 in personal records (it should be the latter)?

As an alternative, is ["high score"](https://www.definitions.net/definition/high%20score) appropriate here? "You got a new high score!"

**Comment by agateau** [comment]
I have been thinking for a while about this one and I decided I am going to sidestep the problem by making the car say a more generic congratulation sentence. To make it more interesting I am going to add 5 or 6 sentences, which will be picked randomly.
