### ISSUE TITLE
One button text is overflowing

### ISSUE THREAD

**Issue by agateau** [agateau/pixelwheels#145]
Hey @PandaCoderPL, I played with the Polish translation last week, and noticed some texts are a bit too long and are overflowing their buttons. I fixed a few of them by slightly reducing the font size and by replacing the text of the switch button items with ⏽/ ⭘ labels, but for one button there is not much I can do, see attached screenshots.

![image](https://user-images.githubusercontent.com/3575/137679458-fe34dbc9-ae0c-45bd-b27c-6a776c80ebfe.png)

Can you look at it?

**Comment by agateau** [comment]
> Also on the same image I see another issue. For some reason letters "ą", "ć", "ę", "ł", "ż" and "ź" are not rendered. Letter "ó" shows without any issues though but I saw it being used in other languages as well so that may be the reason. I think the whole issue is related to #137.

Oh, thanks for letting me know about this. There are two levels to take into account here:
- The font must contain all the required glyphs
- Pixel Wheels must declare all the glyphs to render: libgdx-freetype, the library used to render texts using truetype fonts, expects a list of the glyphs

This means it might be possible to use the existing font for Polish, if it is only a matter of declaring the required glyphs. I am going to investigate this.

**Comment by agateau** [comment]
Missing characters have been fixed. Can you try the latest builds from https://builds.agateau.com/pixelwheels? I noticed some buttons are a bit wide now, but a simple fix is to split the text with an `\n`.

If you make the changes from a computer you should be able to test the changes directly, without rebuilding Pixel Wheels. I documented the way to do this in the [translation doc](https://github.com/agateau/pixelwheels/blob/d5466b9694531154a1e6cae9033a4564d6e1ed0c/docs/translations.md).

**Comment by PandaCoderPL** [comment]
> Missing characters have been fixed.

Unfortunately not all of them. For example in General settings tab, the word "audio" is displayed as "dwik" instead of "dźwięk" which is the same issue as before.

> Can you try the latest builds from https://builds.agateau.com/pixelwheels? I noticed some buttons are a bit wide now, but a simple fix is to split the text with an `\n`.

I installed build `itchio-0.21.0+20210711T191444-45f9969` and the only issue I see is "visit support page" button in About tab in settings. In this case the text slightly overflows the button. If needed I could change translation from "odwiedź stronę wsparcia" ("visit support page") to "strona wsparcia" ("support page"). Let me know which buttons are bit wide now and tell me on what device you see this. I'm using Google Pixel 4a and like I said before, I don't really see any other issues than those mentioned above.

> If you make the changes from a computer you should be able to test the changes directly, without rebuilding Pixel Wheels. I documented the way to do this in the [translation doc](https://github.com/agateau/pixelwheels/blob/d5466b9694531154a1e6cae9033a4564d6e1ed0c/docs/translations.md).

Unfortunately I'm doing everything from my phone so I'm not able to test translation directly.

**Comment by agateau** [comment]
> Unfortunately not all of them. For example in General settings tab, the word "audio" is displayed as "dwik" instead of "dźwięk" which is the same issue as before.

That must be because titles use a different font. That font must be missing glyphs compared to the main font. The quick fix is to use the same font as the text, that would be less nice, but more correct. The better fix would be to find a more complete title font :thinking: .

> Let me know which buttons are bit wide now and tell me on what device you see this. I'm using Google Pixel 4a and like I said before, I don't really see any other issues than those mentioned above.

I mainly test on my computer, and indeed that is the button I was thinking of. It looks like this for me:

![image](https://user-images.githubusercontent.com/3575/140818409-9f086368-805f-4c9c-aabc-2b2ef1b861d8.png)

> Unfortunately I'm doing everything from my phone so I'm not able to test translation directly.

Ah too bad. I think I can't make this work on Android because Pixel Wheels would need to request more permissions to be able to read files outside of the apk.

**Comment by PandaCoderPL** [comment]
> That must be because titles use a different font. That font must be missing glyphs compared to the main font. The quick fix is to use the same font as the text, that would be less nice, but more correct. The better fix would be to find a more complete title font 🤔 .

In my opinion you should temporarily change title font to text font and change it again when you will find more complete title font in future.

> I mainly test on my computer, and indeed that is the button I was thinking of. It looks like this for me:
> 
> ![image](https://user-images.githubusercontent.com/3575/140818409-9f086368-805f-4c9c-aabc-2b2ef1b861d8.png)

Now I see. Do you think making the second text shorter will make both buttons narrower?

> Ah too bad. I think I can't make this work on Android because Pixel Wheels would need to request more permissions to be able to read files outside of the apk.

No worries, I can't test the translation but more less I know what could fix the issue so testing is not really needed.
