### ISSUE TITLE
Stuck in the circuit.

### ISSUE THREAD

**Issue by franciscot** [agateau/pixelwheels#16]
I got stuck inside the circuit without a chance to restart:

![screenshot_20180211_125622](https://user-images.githubusercontent.com/5504418/36073103-4f373ebc-0f2b-11e8-94e2-bb34102bf940.jpg)

**Comment by agateau** [comment]
Oups, good catch, going to close that gap!

Meanwhile you can restart the game by pausing it with P, then clicking "Restart".
