### ISSUE TITLE
How to define multiple plural forms?

### ISSUE THREAD

**Issue by PandaCoderPL** [agateau/pixelwheels#160]
When testing my Polish translation I realized that some words should use different plural forms depending on the number. For example word "record": in English you would use "record" (n=1) or "records" (n>1) but in Polish you would use "rekord" (n=1), "rekordy" (5>n>1) or "rekordów" (22>n>4). I'm not sure if the player is able to break more than 4 records at one time but information about defining multiple plural may be useful in future anyway.

**Comment by agateau** [comment]
This was supposed to work, but:
- For some reason the formula was wrong in the pl.po file
- There was some bug in my implementation, I managed to not copy the right formula :facepalm: 

Going to open a PR for this, thanks for letting me know!

**Comment by PandaCoderPL** [comment]
> This was supposed to work, but:

Not really because I forgot about multiple plural forms so the translation was wrong at the start.

> * For some reason the formula was wrong in the pl.po file

It's my fault. When I was translating your game to Polish I basically didn't know what to do about the formula so I copied it from French translating.

> * There was some bug in my implementation, I managed to not copy the right formula 🤦

No worries.

> Going to open a PR for this, thanks for letting me know!

I think I will need to open one as well. Polish translation is missing some strings now and needs few fixes.
