### ISSUE TITLE
"Chinese" string in the language selector is not translated

### ISSUE THREAD

**Issue by agateau** [agateau/pixelwheels#166]
When selecting a language, the string in the language selector must be translated to the target language. I did not do it for Chinese because I don't know how to spell it. This string is defined in languages.xml, in the `name` attribute of the zh_CN element: https://github.com/agateau/pixelwheels/blob/693fd74bf5d4be34a0029cf7a209b861571a35e1/android/assets/ui/languages.xml#L7.

@OliverLew do you have time to look into this?

**Comment by OliverLew** [comment]
Seams easy. It should be "简体中文", for Simplified Chinese, and "zh_CN" locale.

"Chinese" alone should translate to "中文". Sufficient, but not accurate for the locale. I would suggest "简体中文".

**Comment by agateau** [comment]
Thanks, going to integrate it.
