### ISSUE TITLE
rocket stuck in 'let it snow'

### ISSUE THREAD

**Issue by her01n** [agateau/pixelwheels#174]
## Describe the bug

I was playing with the rocket and managed to get so stuck, the car was not able to move at all. I had to quit to menu to continue.

### How to reproduce

1. Select quick race, car rocket, and level let it snow
2. Hit the wooden in the rigth way

### Expected behavior

I should be able to reverse back to track and continue to play

## Information about your build

Pixel Wheels version: 0.21.0

Binary origin:
- [ ] itch.io
- [ ] Google Play
- [x] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version: 10, lineageos 17.1-20211123-microG-avicii

## Optional information

I am attaching the screenshot.
![Screenshot_20211209-210743_Pixel_Wheels](https://user-images.githubusercontent.com/10198016/145470599-068bcd29-7136-40fe-a63e-f91565bfbdef.png)

**Comment by agateau** [comment]
Wow, wheels and body should not be on different sides of the trunk :)

Thanks for the report. Going to look into it.
