### ISSUE TITLE
New translation (RU)

### ISSUE THREAD

**Issue by Nickoriginal** [agateau/pixelwheels#190]
Hello, Russian is my native language so I`ve prepared new Russian translation. Can I help you?

**Comment by agateau** [comment]
That's great! Are you familiar with pull requests? If so, then it's the best way to share your work. If not, no worry, you can send it to me via email (mail@agateau.com).

**Comment by Nickoriginal** [comment]
Okay, thanks! I'll try to send it tomorrow.

**Comment by Nickoriginal** [comment]
Hm, I can do this now!
