### ISSUE TITLE
Add keyboard input for Android

### ISSUE THREAD

**Issue by ncuxonaT** [agateau/pixelwheels#20]
Hi! Could you please add keyboard input support in Android app?

**Comment by agateau** [comment]
Good idea, going to look into it.

**Comment by agateau** [comment]
Regarding this: how do you use the keyboard? Is it a bluetooth keyboard or an USB one with an OTG cable? I am asking this because I haven't tried it yet but looking at the code it should already work.

**Comment by ncuxonaT** [comment]
Hi! I've tested bluetooth and USB-OTG keyboards, both works the same. I can browse menu with keyboard only except the part with "next" and "previous" buttons as they are not selectable. Only two keys seem to work in game: "P" opens menu, "S" pauses game for a second (taking screenshot perhaps?).

**Comment by agateau** [comment]
So the arrow keys on your keyboard do not work in game? Going to try this. I think I have an OTG adapter somewhere. Regarding the "S" key, you are right, it takes a screenshot.
