### ISSUE TITLE
restart drops sound untill app restarted

### ISSUE THREAD

**Issue by NESC1US** [agateau/pixelwheels#22]
Hi, cool game, but restart button drops sound. Version 0.12.0 from f-droid

**Comment by agateau** [comment]
Indeed. I am about to release 0.13.0, which still has this bug, but I am going to look into it for the next release.

Thanks for your report.

**Comment by Wilker-a** [comment]
in the version 0.13.0 (from F-Droid), i think the issue still persists whenever you restart the race, with the temporary fix being going to menu and restarting from there
