### ISSUE TITLE
Hang on weak smartphones.

### ISSUE THREAD

**Issue by userkilled** [agateau/pixelwheels#23]
When I play, sometimes the game freezes, it’s not very convenient to play, as if frame skipping.

**Comment by agateau** [comment]
That's annoying, indeed. What is the model of your smartphone?

**Comment by userkilled** [comment]
It was a disposable 'action'. Leagoo KIICAA POWER, android 7.0.

**Comment by agateau** [comment]
This does not look like the most powerful device, indeed. It would be interesting if you could enable debug mode (go to Settings > Misc > Developer Options > Debug > Show debug hud) and post a screenshot of the text which appears on the left of the screen while racing.

**Comment by userkilled** [comment]
It was once, maybe the problem is in other programs, and not in yours.

**Comment by agateau** [comment]
OK, going to close this then.
