### ISSUE TITLE
Log folder fails on Windows

### ISSUE THREAD

**Issue by Eiim** [agateau/pixelwheels#237]
## Describe the bug

When attempting to open the log folder, it quietly fails.

### How to reproduce

1. Click on "Open log file folder" when running under Windows.

### Expected behavior

The folder would open.

## Information about your build

Pixel Wheels version:

Latest master build

Binary origin:
- [x] https://builds.agateau.com/pixelwheels/

OS:
- [x] Windows

OS version: Windows 10 Home 21H2

## Optional information

The console logs the following information:
```
[PlatformUtils.openURI] 02:03:58.044 Gdx.net.openURI() failed
[PlatformUtils.openURI] 02:03:58.044 Trying with 'start C:\Users\ethan\.cache\pixelwheels'
[PlatformUtils.openURI] 02:03:58.051 Command failed: java.io.IOException: Cannot run program "start": CreateProcess error=2, The system cannot find the file specified
```

The correct command to open a folder in Windows is `explorer.exe path\to\folder`.

**Comment by Nickoriginal** [comment]
Duplicate of #225. Please check that your issue is not duplicate, at least at the first page.

**Comment by Eiim** [comment]
Apologies. I did a search, but for some reason must have used the wrong keywords or something.
