### ISSUE TITLE
Please change the control input

### ISSUE THREAD

**Issue by CrimsonFork** [agateau/pixelwheels#25]
The game (or what's yet there of it) is fun so far, thanks for that, but the control scheme (Smartphone) is… not immersive. My suggestion would be to either use the gravity sensor for stirring and de-/accleration, or at least to have the buttons for stirring on their corresponding side of the screen. Maybe different options in the settings would be helpful. Speaking of options, one for reversing the stirring direction when going backwards would be cool as well.

**Comment by agateau** [comment]
I am not sure why you would want reversing the steering when going backwards: it's done this way to match how a steering wheel works.

I agree with the need for other input modes. I plan to add two:
- steering buttons on the side
- accelerometer based

**Comment by OffifialMITX** [comment]
I know very well that that's how a stirring wheel works, however, in my experience, especially with that rotation-fixed top-down view, it takes very much ressources to rethink why pushing the same button makes the car rotate in the different direction all out of the sudden.

That behavior makes perfect sence in an environment where the size of the wheels is relevant, which, in the given scenario, certainly isn't.

Also the fact that you aren't actively pushing forward in the first place makes it more difficult as well, which separates it more to the feeling of flying a drone that can rotate, than driving a ground based vehicle with respective physics.

Having said all that, I don't think that would have been an issue as much, if I wouldn't have to think about where the ←/→ buttons at all times in the first place.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by agateau** [comment]
Here is a screenshot of the upcoming new touch input control:

![new-hud-buttons](https://user-images.githubusercontent.com/3575/63351326-51037000-c35f-11e9-93c2-f2049066c125.png)

**Comment by OffifialMITX** [comment]
Maybe consider a little more padding to the bottom?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OffifialMITX** [comment]
Also where is the backwards button? I think it's very much needed in some scenarios.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OffifialMITX** [comment]
I forgot to add that it looks cool otherwise.

**Comment by agateau** [comment]
I tried adding a backward button in the middle between the left and right buttons, but it was really awkward to use. I ended connecting backward to "press both left and right together". This means you can't go backward and in a direction at the same time, but it felt better.

I am probably also going to add an "analog pad" or "slider" input control where you drag your left thumb left and right to steer and have a classic "brake" under your right thumb.

I experimented with an accelerometer-based input control, but I think it does not work. It does not map well to a top-down game. I'd be interested if any of you know of a top-down game with good accelerometer-based control.

**Comment by OffifialMITX** [comment]
Ok, so I have some crazy ideas.
1. Instead of for stirring, use the acclerometer as a direction pointer which the car snaps to. Horizontal position is neutral, and everything else points to a direction. The only not janky use of an acclerometer I've seen sp far is in those different variations of the thing where you control a marble, sp, essentially, it's just that.

2. As mentioned in another issue one could use the volume buttons as sort of a shoulder trigger on most devices. But I think that only using either of those buttons would make sense, not assigning both to different functions. Imo a brake there makes the most sense.

3. While not a top-down game per se, Geometry Dash has a very interesting way of controlling the kimd of freeform y-position modes. The Wave and Ship, while having different physics, are controlled by one button and generally go up when pressed and down when not. So, I realize that it'll probably be very unintuitive to get used to, but maybe it'll be actually useful, if th3 car stirrs left by default, there is a button [→↓(right-handed layout)] to stir right instead, a button to not stir above it [→] and a brake button [↓←].

**Comment by Wilker-a** [comment]
i would like to add to this topic :3

i have an idea for on-screen turn controls, and while it needs some polishing, i think it would be great to have this in the game.

##### the idea is that the turn should have the shape of two bars overlapping like a cross.

- the first one, a vertical bar, occupies the height of the controls, representing acceleration/brake, and sits at the center of the second bar. (hereafter, "Blue" and "Blue bar")
  - the width of Blue represents the steer control's lower deadzone (minimum treshold before turning), which can be changed.
    - the default deadzone for turning should be 0, and with that, the Blue bar becomes just a vertical line.

- the second one, a horizontal bar, occupies the width of the controls, representing the steer controls. sits at the center of the height of the first bar when idle. ("Orange", "Orange bar")
  - the height of Orange, represents the acceleration/brake control's lower deadzone (minimum treshold before accelerating or breaking), which may be changed.
    - the default deadzone for accelerating should be a couple of pixels. but no matter the default value, if it is kept at the default value, the height of the Orange bar should be a third of Blue's height.

- whenever the player is controlling the car, Orange should always follow the touch,
  - the height of the Orange bar should follow the Y position of the touch, with its limits being the height of Blue;
  - whenever the player is turning, a bar should fill the Orange bar, starting from the center, up to the X position of the touch;

- whenever the player controls the acceleration and brake ("Torque"), a blue rectangle should give the visual cue of the limits of this control. (the explanation now would probably be about how i imagine it rendering, 'cause idk how to explain better \^\^')
  - two blue rectangles with Blue's width, occupying the first 1/3, and the third 1/3 of Blue's height, masked by Orange. that means that they will only be visible inside of the area of Orange, making it a faster visual cue for the limits of the vertical controls.

##### With all that said, here's a visual example. it is a sketch i tried to make to make it easier to understand somehow.
![a visual example of the two bar controls](https://user-images.githubusercontent.com/10854855/64469373-44c13600-d107-11e9-9e6f-83aebb8a2d5a.jpg)

what do you think? \^w\^

also please reply if you have any questions \^\^

**Comment by agateau** [comment]
I am not sure I get it, but it feels like a virtual analog stick to me.

**Comment by Wilker-a** [comment]
it actually is, but i think it would avoid the confusion of, for instance, having a circle to represent two completely different kinds of controls (torque and direction) like in games such as SuperTuxKart, while still keeping them together in a single button.

the main problem i find with analog sticks for this is that it makes it hard to just find the point where you can turn to a direction completely while still keeping the acceleration. the result is that at many times you end up losing speed while turning.
![a gameplay screenshot of SuperTuxKart for reference](https://user-images.githubusercontent.com/10854855/64496345-60008280-d27a-11e9-8b49-9d3d011ec114.png)

the idea is that the information of both controls are kept visible without having to limit it to a d-pad, for example.

**Comment by OffifialMITX** [comment]
I think that this is overcomplicated. Pretty much the same would be achieved with a translucent area that where x is stirring and y is de-/accleration, with 0 in the middle (or maybe ⅔ from top?) and autolock to x=50% and y=0% (from top).

Generally however, I am against any sort of analog input on a touchscreen, since one has no tactile feedback so it requires you to look directly at the controls, instead of your character. Personally, for me it doesn't feel anywhere near good on Replica Island, SuperTuxKart nor Minetest.

With binary input, like buttons, you may have less precise control, but, once you have memorized their position, you have tactile feedback (whether you're pressing) which is a much better flow for a fast-paced game.

On a side-note, Mindustry has an interesting control scheme, where you can move your view-port freely and your vehicle flies at it's speed to the center of the viewed scene. Though I don't think it'd fit Pixel Wheels.

**Comment by Wilker-a** [comment]
that's understandable.

but if you think about it though, it's just a rectangle-shaped analog stick, just like the one you have just described. in fact, you can actually make it just a rectangle, and it will still be just as easy as a d-pad, while keeping the precision of an analog stick, but without the confusion of a circle-shped one.

![a rectangle-shaped driving control scheme. the red and blue lines inside of it intersects at 
the point where the touch happens.](https://user-images.githubusercontent.com/10854855/64532824-a7bdf300-d2e8-11e9-9527-b37dfb715e29.jpg)

as for Mindustry, that might require path tracing, while having to deal with the car stopping all the time depending in how fast the player moves the camera. not sure if it is a good idea.

**Comment by OffifialMITX** [comment]
Don't sweat it, you just gotta try to think putside of the box sometimes. Eventually you'll notice that it's literally just a box. If we were to assemble your description physically I'm sure it'd be great.

The Mindustry example is just a side-note, in fact, it'd be really horrible to have to race like that.

But I've got two other ideas now

1. What if we had a literal stirring wheel, presumeably auto-stirring to front, and moving only relatively to the finger, unlike a D-Pad would.

2. What if we had a wheel thingy that could be either pointed to whereever the finger is relatively to it, or it's pointer can be rotated to show in a global direction, and the car snaps to thatß

**Comment by Zireael07** [comment]
The wheel thing is a good idea! I saw it done in Real Racing 3 as one of the steering options.

**Comment by agateau** [comment]
I think a rectangular analog stick is doable, I will experiment with it.

**Comment by Obsidien** [comment]
I like the current control input :cry:, and I’d be missing the ability to control backward direction. Is there a way to keep it as an option, or is your code not structured for doing that?

**Comment by agateau** [comment]
@Obsidien I am not removing the current control input: I am adding a new one.

**Comment by Obsidien** [comment]
Perfect then. :smiley:

**Comment by Wilker-a** [comment]
i don't think that a rectangular (or square-shaped?) analog stick would limit the ability for doing reverse driving
