### ISSUE TITLE
keep the previous version of the harvester？

### ISSUE THREAD

**Issue by yzqzss** [agateau/pixelwheels#26]
Because the harvester is not easy to control, I can compensate for the control defects by hitting other vehicles or walls, making it faster than other vehicles.  

For example, when driving at high speed, hit the wall at an angle to drive it at the correct speed and direction.Make the transfer does not affect the driving speed.

This is very challenging, I have been using the harvester to challenge the "do not slip" and "blocky rown" minimum completion time.

But the new version makes the harvester easier to handle, making it less unique and challenging.

Can keep the previous version of the harvester?I like it. 

![Screenshot_20190816-171754-465.jpg](https://i.loli.net/2019/08/16/Xq4UG3VYEhZuPpm.jpg)

**Comment by BrianGaucher** [comment]
I have found that the rocket is quite difficult (yet rewarding) to handle, if you are looking for a challenge, try it, i have managed 40:06 with the rocket, and 39.99 with the harvestor.

**Comment by agateau** [comment]
Hi yzqzss, I received quite a few feedback before regarding the harvester being too hard to control, so I am not going to change it back, sorry for that.

Also, I am curious what you mean with this:

> the "do not slip" and "blocky rown" minimum completion time
