### ISSUE TITLE
The Chinese font file needs update with .po file

### ISSUE THREAD

**Issue by oliverlew** [agateau/pixelwheels#297]
## Describe the bug

New translations in zh_CN is not shown due to the subset font file is not updated.

### How to reproduce

1. 
2. 
3. 

### Expected behavior

All characters are shown in game.

## Information about your build

Pixel Wheels version:

Binary origin:
- [ ] itch.io
- [ ] Google Play
- [x] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version:

## Optional information

Suggest to put `tools/fonts/generate-fonts` script somewhere in the build process.

**Comment by oliverlew** [comment]
On Tue, Dec 06, 2022 at 12:00:55AM -0800, Aurélien Gâteau wrote:
> Thanks for the report. I am going to look into it. Can you point me to which screens have missing characters?

Mainly the car selecting and map selecting screens, where most new
translations take place. For example, some map names only show '！'
in Chinese.

I have confirmed the subset font file embedded in the apk indeed lacks those
glyphs. Re-run the font generating script should add the missing ones.

**Comment by agateau** [comment]
Thanks for the extra info. This is fixed now.
