### ISSUE TITLE
Bunch of glitches

### ISSUE THREAD

**Issue by OffifialMITX** [agateau/pixelwheels#30]
- Speed-navigating through the menu, especially right after starting the app can lead to some assets not being loaded. Mostly sounds, but I also had a case once where the map textures didn't load at all.

- Sometimes sound decides to comit homicode on my ears, by completely overdriving the current audio output. Seems to happen on random, but more never happens on first race.

- The cars drive very differently the first time after app start compared to any following time, which makes going for better times a little frustrating.

- Using the pause menu restart button removes any sound for the current race.

- Having multiple attempts (often restarts via going to the home menu and re-entering) progressively makes the game run slower (fps and response time).

- Launching a rocket at a booster results in you being faster than the rocket.

- Going out of and back in the app while in the pause menu makes the pause button go a little lower.

- The last level can be cheesed very badly if, after the first turn you go down into the hole with the missing hitbox and drown near the bridge repeatedly. There's also a missing hitbox right after the last booster.

- The rocket launcher constantly makes collision sounds, but only with the human player.

- The lap counter stays at 1 even if making negive laps.

- If staying in the deep water for too long, but still making it out eventually, an additional helicopter pops up that stays at that place indefinetely.

**Comment by OffifialMITX** [comment]
- The care are able to turn the wheels before the counter has cpunounted down
- The rocket and traktor have especially weird consequences, with the rocket can't even start on it's own on some tracks. Or sometimes it gets stuck somewhere on the track

- Which results in an overflow (apparently) and leads to absurd negative finishing times on the result board
- Sometimes, when a car hits your still attached mine you get a boost, probably due to the spin. Not game-breaking, but seems unintended.

**Comment by OffifialMITX** [comment]
- If a mine is pushed into you the moment you plant it you trip over it yourself

- If you trip over a mine but another car pushes you that moment, you don't loose any speed / don't enter the spin animation

**Comment by agateau** [comment]
I value your enthusiasm and your feedback, but I cannot work with multi-topic issues. You need to open one issue per bug, and check if they have not already been reported.

**Comment by OffifialMITX** [comment]
Ok, sorry. It's just so much that I thought I'd rather not clutter the issues page. But ok.

On 21 August 2019 15:55:49 GMT+02:00, "Aurélien Gâteau" <notifications@github.com> wrote:
>I value your enthusiasm and your feedback, but I cannot work with
>multi-topic issues. You need to open one issue per bug, and check if
>they have not already been reported.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/agateau/pixelwheels/issues/30#issuecomment-523468129

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
