### ISSUE TITLE
on river map, helicopter drops you again in the water

### ISSUE THREAD

**Issue by boopdadm** [agateau/pixelwheels#302]
On river map, if you fall in the river beside the bridge, helicopter comes to retrieve you.
It then drops you on the bridge and you slide and fall again in the water.
This is an endless loop:
You fall one side, the helicopter drops you the other side, you sink, the helicopter drops you the other side...
🙂

**Comment by agateau** [comment]
Ooooh, that's a fun one! Going to look into it.
