### ISSUE TITLE
Split-Screen Multiplayer

### ISSUE THREAD

**Issue by hendursaga** [agateau/pixelwheels#308]
The current implementation, where the camera is constantly zooming in and out as the two players get closer or farther from each other, is extremely disorienting and impossible to play. I've tested this with a few friends and they all agree, split-screen would definitely be better.

I hope it won't be too great of an architectural change??

**Comment by agateau** [comment]
Hi Hendursaga,

Pixel Wheels used to have a split-mode, but it was difficult to play because unlike a 3d game like Mario Kart, players could not see very far away when going in the left or right direction. Maybe the zoom needs to be tweaked to be less violent :thinking:. I think the real solution would be to implement network play, but I am a bit afraid of opening this Pandora box...

**Comment by hendursaga** [comment]
> unlike a 3d game like Mario Kart, players could not see very far away when going in the left or right direction.

I suppose that would be a concern on a small screen, but what's preventing you from having both split screen AND (less violent) zooming?

**Comment by agateau** [comment]
The problem is: the game would have to zoom out a lot (not necessarily violently) to get the same depth of view, and then the vehicles end up being very small :/

**Comment by hendursaga** [comment]
Hmmm? You mean you would HAVE to have the exact same zoom factor for all players?

**Comment by agateau** [comment]
No, that's not what I meant. Let's say that at a given speed, the player must be able to see N tiles in front of them for the game to remain playable. When the view is half or a quarter of the screen, being able to see N tiles is going to require zooming out a lot more.

**Comment by hendursaga** [comment]
OK, that makes sense! I was thinking of playing it split-screen on a very large TV monitor, so I don't think it should be a problem, but I understand if you'd want to go other routes, like networking.

**Comment by agateau** [comment]
For info: I changed my mind on this (see https://agateau.com/2023/split-screen-revival-progress/), and it's mostly done now :)

**Comment by agateau** [comment]
It's actually done now :wink:
