### ISSUE TITLE
Some stuff that I feel like would improve the experience. At least for me, but probably others as well.

### ISSUE THREAD

**Issue by OffifialMITX** [agateau/pixelwheels#31]
- An in-game speedometer, maybe as an arrow fixed on the car, I quite like the velocity display option, as it makes up for the "lost" precision visibility that you'd have in a fp3d view
- Make stuff more "slide-y", as in it doesn't feel natural to me at all to loose all of the velocity by hitting a corner, and being completely stopped by a wall, even if you try to push by at a 45° angle.
- Don't make the player automatically faster than every other competitor. It feels just unfair and too OP.
- give a little but noticeable slowdown for carrying a mine, so that one is either safer (from a rocket) but slower or faster but at more risk.
- make the camera zoom slower, so that it's not as distracting and disorienting at speed changes, especially the zoom-in.
- make the rocket less aiming- and more homing-based, so that it is realistic to dodge it if shot from a larger distance
- add stat visibility to the cars
- the volume keys could be used as sort of a shoulder button on most devices. Maybe assign the brake there?
- Add a feedback for hitting your opponents, so you know that e.g. the off-screen mine has been triggered.
- Maybe add a bonus of sorts for hitting the opponents, to encourage more aggressive gameplay?

**Comment by OffifialMITX** [comment]
- I don't think that just driving in a straight line over ice should slow you down.

**Comment by agateau** [comment]
I value your enthusiasm and your feedback, but I cannot work with multi-topic issues. You need to open one issue per bug, and check if they have not already been reported.
