### ISSUE TITLE
Driving feature suggest

### ISSUE THREAD

**Issue by Ygarr** [agateau/pixelwheels#322]
When car goes from top to down we have 
that Left key make move to the Right. And right key - > make move to the left.

Suggest optionally 
give ability to change keys (left and right) when car make turn around larger than 180 degrees.(after release key)

**Comment by agateau** [comment]
Hi, sorry for the late reply. I think this behavior would be surprising: when the car angle is at the limit between the change, and the player wants to turn, they would need to look closely at the car angle to decide which key to press.
