### ISSUE TITLE
Xbox One Controller Not detected

### ISSUE THREAD

**Issue by uditsehra** [agateau/pixelwheels#323]
It's not recognizing the Xbox controller.

### How to reproduce

1. Connect xbox one controller via Bluetooth
2. Change control setting to gamepad
3. Play game and it'll say "Player 1 gamepad not detected"

### Expected behavior

What should have happened instead?
I should be able to play game using xbox controller.

## Information about your build

Pixel Wheels version:
0.24.2

Binary origin:
- [x] Other: Flatpak

OS:
- [x] Linux

OS version: Ubuntu 22.10

## Optional information

If relevant, add screenshots to help explain the bug.
![Screenshot from 2023-02-08 16-12-04](https://user-images.githubusercontent.com/47755446/217509318-f74387c1-c2df-47d6-bb0d-26529b2f3445.png)

![Screenshot from 2023-02-08 16-12-28](https://user-images.githubusercontent.com/47755446/217509369-94c621c8-732b-4a58-a7f4-816244f8d4a5.png)

![Screenshot from 2023-02-08 16-22-27](https://user-images.githubusercontent.com/47755446/217509597-0f506213-562b-4c03-8c9e-a208264ae9fc.png)

## Additional context

If you generated a log archive from the game, you can attach it to this report.

**Comment by agateau** [comment]
It's possible the Flatpak package is missing some permissions to access game controllers. Can you try the binary release to check if it works better?

**Comment by uditsehra** [comment]
Yes the binary release is working excellent. Thank you.
