### ISSUE TITLE
italian translation ready, but not compiled

### ISSUE THREAD

**Issue by chipechop** [agateau/pixelwheels#325]
Hi, I was a Java developer in 1999 (...) don't have any compiler today.

I translated the three attached files, WITHOUT BUILDING THEM, just copied and pasted the english versions and translated them, so for instance, the comments with the line numbers are wrong...

Are the three attached files, useful anyway?

[it_IT.po.txt](https://github.com/agateau/pixelwheels/files/10735455/it_IT.po.txt)
[credits.gdxui.xml.txt](https://github.com/agateau/pixelwheels/files/10735456/credits.gdxui.xml.txt)
[languages.xml.txt](https://github.com/agateau/pixelwheels/files/10735457/languages.xml.txt)

**Comment by agateau** [comment]
Hi chipechop!

Thanks a lot for this translation, it looks good!

![screenshot-2023-02-15-090835 688](https://user-images.githubusercontent.com/3575/218970244-8e70b077-dd21-499e-9ce1-3a9643a64753.png)
![screenshot-2023-02-15-090842 828](https://user-images.githubusercontent.com/3575/218970266-04c37093-d4e9-490f-ae91-6f5d75147575.png)
![screenshot-2023-02-15-090859 715](https://user-images.githubusercontent.com/3575/218970268-a05ea52c-66ce-4692-9ccc-bce6884ac365.png)

I just merged your work (#328). You should be able to try the game by downloading it from https://builds.agateau.com/pixelwheels when the CI is done building it (https://github.com/agateau/pixelwheels/actions/runs/4181867141).

Regarding compilation, the good news is: you don't need to compile the game to work on your translation. Pixel Wheels directly loads .po files, see https://github.com/agateau/pixelwheels/blob/master/docs/translations.md#testing-a-translation for more details.

Thanks again!

**Comment by agateau** [comment]
Hi @chipechop,

I am about to release a new version of Pixel Wheels, can you update your translation?

I have been trying to reach you via the email you added to the .po file, but it bounces :(
