### ISSUE TITLE
Crash: Falling when selecting the 'Up' button on the TV remote control

### ISSUE THREAD

**Issue by userkilled** [agateau/pixelwheels#326]
## Describe the bug

Explain what went wrong

### How to reproduce

1. Settings
2. Control
3. Keyboard
4. settings
5. Change on 'Up'
6. Crash

### Expected behavior

What should have happened instead?

## Information about your build

Pixel Wheels version:

Binary origin:
- [ ] itch.io
- [ ] Google Play
- [ o] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [ 4.4] AndroidTV
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version:

## Optional information

If relevant, add screenshots to help explain the bug.

**Comment by agateau** [comment]
Thanks for the report, just fixed it.
