### ISSUE TITLE
The shortcut off the main road is found on the 'Flood' track after starting the race

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#336]
## Describe the bug

The shortcut off the main road is found on the 'Flood' track after starting the race.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Tap the 'Quick Race' button.
3. Double tap the third track ('Flood').
4. Double tap the first car ('Red Lightning').
5. Go forward past the water instead of turning left.
6. Go past the hole between the wall and the tires.

### Expected behavior

No shortcuts off the main road are found on the 'Flood' track.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [ ] itch.io
- [x] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version: Android 11 RP1A.200720.011
Device: Xiaomi Redmi 9 M2004J19AG

## Optional information

Video: https://drive.google.com/file/d/131auSN7czzzyQLFkQUAFWMIzkDzZnzqd/view?usp=share_link

**Comment by agateau** [comment]
Good catch! Going to close that hole. Thanks for the report, the video was really helpful :+1:.
