### ISSUE TITLE
The free camera is stuck at the game level after activating it in developer tools

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#338]
## Describe the bug

The free camera is stuck at the game level after activating it in developer tools.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Tap the 'Settings' button.
3. Tap the 'Under the hood' tab.
4. Tap the 'Dev. Options' button.
5. Tap the 'Free camera' button.
6. Tap the 2x left arrow at the bottom of the screen to go back to the main menu.
7. Tap the 'Quick Race' button.
8. Double tap the 1st track ('Welcome!').
9. Double tap the 1st car ('Red Lightning').
10. Pay attention to no control over the free camera.

### Expected behavior

The free camera is not stuck at the game level after activating it in developer tools.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [ ] itch.io
- [x] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version: Android 11 RP1A.200720.011
Device: Xiaomi Redmi 9 M2004J19AG

## Optional information

Video: https://drive.google.com/file/d/13UpstVFNZlmZSSwXY-tB1letC0d0h8JY/view?usp=share_link

**Comment by agateau** [comment]
Hi, the free camera can be moved using Vim keys (HJKL). It's really a debug tool, but I should document this.

**Comment by lukmarcus** [comment]
> Hi, the free camera can be moved using Vim keys (HJKL). It's really a debug tool, but I should document this.

It could also be written with small letters below Free Cam on Android build, that this tool will not work without the keyboard.
