### ISSUE TITLE
Next button after tournament unresonsible on FDroid

### ISSUE THREAD

**Issue by Anachron** [agateau/pixelwheels#34]
As title says: When I finish a tournament on F-Droid the next button after the highscore-list (1st, 2nd, 3rd) is unresponsive. I realized as workaround I need to lock my screen and unlock again.

Ps.) Funny mini-game! I'd love to get a bit smarter AI though. :-)

**Comment by agateau** [comment]
That is strange, I can't reproduce it. Does it happen when you rank in the top 3 or when you rank after 3? Can you try to reproduce it on another device?

**Comment by Anachron** [comment]
Okay I played very bad in order to reproduce this issue and it does not happen when I'm not in top 3 score. 

If it helps: I am on `Android 9.0`, `4.4.111` is the kernel and my phone is a `Samsung Galaxy A40`.

**Comment by Knusper** [comment]
I can confirm this bug. I don't use the default screen ratio. It happens when I finish in top 3.

**Comment by agateau** [comment]
@Knusper Which version of Pixel Wheels do you have?

**Comment by Knusper** [comment]
0.13.0

**Comment by agateau-g** [comment]
Can you try with 0.14.1? I think it got solved.

**Comment by Knusper** [comment]
This version is not on fdroid 0.13.1 is the latest version I see:
https://f-droid.org/de/packages/com.agateau.tinywheels.android/

Am Mo., 18. Nov. 2019 um 09:26 Uhr schrieb Aurélien Gâteau <
notifications@github.com>:

**Comment by Knusper** [comment]
Can you please publish the version that fixes the bug in f-droid?  I really like this game

**Comment by agateau** [comment]
I can't really "publish" on F-Droid: F-Droid is supposed to rebuild the new version as soon as it is tagged. Need to check with them what went wrong.

**Comment by Knusper** [comment]
> I can't really "publish" on F-Droid: F-Droid is supposed to rebuild the new version as soon as it is tagged. Need to check with them what went wrong.

I think here would be a good place to report it:
https://gitlab.com/fdroid/fdroiddata/issues

**Comment by Knusper** [comment]
Just got 0.14.1 via F-Droid and the next button now works ... Thanks!

**Comment by agateau** [comment]
Thanks for the update :+1:, closing the issue.

**Comment by S-Joao-V** [comment]
I installed the game for the first time via the F-Droid app and received 0.13 by default. Looking under versions the 0.14.1 was available from the start.

**Comment by agateau** [comment]
@S-Joao-V sounds like an F-Droid issue

**Comment by Wilker-a** [comment]
@S-Joao-V easy to solve :3

![just enable Expert Mode in the settings and enable unstable updates suggestions](https://user-images.githubusercontent.com/10854855/72116249-9ee63800-3341-11ea-9cb0-30f8b97867ba.png)

**Comment by agateau** [comment]
Interesting. The question then becomes: why is 0.14.1 marked as unstable? Any idea?
