### ISSUE TITLE
The player vehicle is gone beyond the screen on the multi-player 'Flood' track after creating a big gap between players

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#340]
## Describe the bug

The player vehicle is gone beyond the screen on the multi-player 'Flood' track after creating a big gap between players.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Enter the 'Multi Player' option.
3. Enter the 'Quick Race' option.
4. Select the 'Flood' track.
5. Select cars for both players (Space and Left Control).
6. Play only as Player 1.
7. Pay attention to the camera working.

### Expected behavior

Both vehicles are always seen on the screen regardless of the gap between players.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [x] itch.io
- [ ] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [ ] Android
- [ ] Windows
- [ ] macOS
- [x] Linux

OS version: Ubuntu 22.04.2 LTS

## Optional information

Video: https://drive.google.com/file/d/1vg2lA1aQ89s35gt7W2v8YkOfndirx60x/view?usp=share_link

**Comment by agateau** [comment]
Hi, another nice report :+1:. That one can be considered fixed now that Pixel Wheels is going back to split-screen (see https://agateau.com/2023/split-screen-revival-progress/)
