### ISSUE TITLE
Import/export progress and settings

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#36]
Hi again \^w\^

do you think it would be good to have a function, future-proofed as needed, to easily import and export for and from backup? that would be really good to easily backup info to test stuff or just reinstalling the game without losing the data, or maybe even making it possible to add ghosts.

JSON or other formats readable by text viewers is probably an easy way to have this info parsed, but there may be others that may be good...

what do you think? :3

**Comment by agateau** [comment]
Hi,
This is something I need to think about, because saving progress among devices is becoming more and more an expected feature, but it is tricky to get right without making it super easy to cheat.

I am closing this issue because it is in fact the same problem as #32.
