### ISSUE TITLE
The selected vehicle can be changed by one of the players on the multiplayer screen before the other player selects his vehicle

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#360]
## Describe the bug

The selected vehicle can be changed by one of the players on the multiplayer screen before the other player selects his vehicle.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Click on the 'Multi Player' option.
3. Click on the 'Quick Race' option.
4. Click on the first track.
5. Select any vehicle as the first player.
6. Select any vehicle again as the first player.
7. Pay attention to the possibility of change.

### Expected behavior

The selected vehicle can't be changed by any of the players on the multiplayer screen.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [x] itch.io
- [ ] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [ ] Android
- [x] Windows
- [ ] macOS
- [ ] Linux

OS version: Windows 10 x64

## Optional information

Video:

https://github.com/agateau/pixelwheels/assets/1151664/1b807b1e-6b21-4c8e-b108-86e43a6a72ea

**Comment by agateau** [comment]
I am closing this report because the screen to select vehicles has been completely rewritten in master, so the bug report no longer applies.
