### ISSUE TITLE
The shadows of buildings, vehicles and weapons are overlayed on each other on the race screen

### ISSUE THREAD

**Issue by lukmarcus** [agateau/pixelwheels#361]
## Describe the bug

The shadows of buildings, vehicles and weapons are overlayed on each other on the race screen. There is only one source of light so this should not happen.

### How to reproduce

1. Open 'Pixel Wheels' game
2. Click on the 'One Player' option.
3. Click on the 'Quick Race' option.
4. Click on the first track.
5. Click on the first vehicle.
6. Drive until you get to the footbridge over the road.
7. Stop the vehicle on the footbridge's shadow.
8. Pay attention to the double shadow (or even triple if there is a weapon on the vehicle).

### Expected behavior

The shadows of buildings, vehicles and weapons are not overlayed on each other on the race screen.

## Information about your build

Pixel Wheels version: 0.42.2

Binary origin:
- [x] itch.io
- [ ] Google Play
- [ ] F-Droid
- [ ] https://builds.agateau.com/pixelwheels/
- [ ] Self-built
- [ ] Other:

OS:
- [ ] Android
- [x] Windows
- [ ] macOS
- [ ] Linux

OS version: Windows 10 x64

## Optional information

Screenshot:

![23061903](https://github.com/agateau/pixelwheels/assets/1151664/aa3b89d0-f270-4fcf-af75-f251744d90e6)

**Comment by agateau** [comment]
You are correct, but fixing that bug would require too much work in the engine, so I am not going to fix it, sorry.
