### ISSUE TITLE
Integer overflow with slow drivers

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#38]
í assume that the final time is calculated using a constant speed tested with the lenght of the map.
i guess it's okay, but whenever i finish a race but one of the opponent (usually the Rocket) is stopped or really slow, a really large number ends up in the leaderboard.

![a screenshot of the scoreboard](https://user-images.githubusercontent.com/10854855/64842636-2fea1400-d5d9-11e9-94f7-760b8340edbc.png)
![another screenshot of the scoreboard](https://user-images.githubusercontent.com/10854855/64842694-69228400-d5d9-11e9-9f17-c7ab78922527.png)

i believe that something like a timeout whenever the line is crossed for the first time, would be a good thing to add. something between 15 to 45 seconds (depending on map length) to finish before the time is out, otherwise the driver is disclassified and a Did Not Finish (with no point gain if on championship) should show up on the leaderboard.

what do you think?

**Comment by agateau** [comment]
Oups, that looks wrong :). You are right that as soon as the player has finished, the race really stops: the times for the vehicles behind the player are extrapolated based on their current time. I need to think about this did-not-finish idea, but for now I am just going to fix that bug.
