### ISSUE TITLE
[F.Req] map maker

### ISSUE THREAD

**Issue by RustoMCSpit** [agateau/pixelwheels#383]
players should be able to make maps in game and distribute them through the game, a vehicle maker would also be cool

**Comment by agateau** [comment]
Similarly to #382, this is not something I want to dive in. There is documentation to create [new maps][] and [vehicles][] though.

[new maps]: https://github.com/agateau/pixelwheels/blob/master/docs/map-format.md
[vehicles]: https://github.com/agateau/pixelwheels/blob/master/docs/vehicles.md
