### ISSUE TITLE
Rockets think they can cross walls (they cannot)

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#39]
It looks like opponents can try to reach you with the “rocket” weapon even if there’s a clear wall between them and you; you’ve the red target on your car, they launch the rocket, but you’re sometimes at the opposite of the circuit. Seen usually on the “third” circuit, where, when you cross the finish line, you can have opponents coming in your direction, while they are only at the 4th curve.

(Thanks for this game, it is really fun, playing on Android.)

**Comment by agateau** [comment]
Agreed, opponents are not really smart, and the rocket is not much better. Will look into making the rocket locking system take walls into account.
