### ISSUE TITLE
Can't play the game on Android in 0.25.0

### ISSUE THREAD

**Issue by Eiim** [agateau/pixelwheels#398]
## Describe the bug

After updating to 0.25.0, I can no longer play the game. Clicking on "Quick Race" or "Championship" shows a message that says "Some controllers are missing."

### How to reproduce

1. Open the game
2. Click "Quick Race" or "Championship"

### Expected behavior

I would enter the level/cup select screen.

## Information about your build

Pixel Wheels version: 0.25.0

Binary origin:

- [ ] itch.io
- [ ] Google Play
- [x] F-Droid
- [ ] <https://builds.agateau.com/pixelwheels/>
- [ ] Self-built
- [ ] Other:

OS:

- [x] Android
- [ ] Windows
- [ ] macOS
- [ ] Linux

OS version: Android 13

## Optional information

![Screenshot_20230908_100807_Pixel Wheels](https://github.com/agateau/pixelwheels/assets/24627058/7462649e-9157-494d-b9d3-60271577307a)

![Screenshot_20230908_100813_Pixel Wheels](https://github.com/agateau/pixelwheels/assets/24627058/0db532a3-f61e-4b46-ba4b-129c7f3fd9dd)

**Comment by agateau** [comment]
Hi, thanks for the report. I was able to reproduce, going to look into it. I was able to workaround it by clicking on the right arrow to change the control method and then back on the left arrow.

**Comment by agateau** [comment]
> Hi, thanks for the report. I was able to reproduce, going to look into it. I was able to workaround it by clicking on the right arrow to change the control method and then back on the left arrow.

Actually I can't reproduce anymore :(. Can you go to "Under the hood" and click on "REPORT BUG" so that it uploads the log file?

**Comment by Eiim** [comment]
I got the log file, but I'm not sure how to attach it here. I made it a file.io link if that works: https://file.io/QbB0eTV626xK

**Comment by agateau** [comment]
> I got the log file, but I'm not sure how to attach it here. I made it a file.io link if that works: https://file.io/QbB0eTV626xK

It worked, thanks!
