### ISSUE TITLE
Time trials? 

### ISSUE THREAD

**Issue by StandWeird** [agateau/pixelwheels#406]
I'm new to GitHub and I'm just wondering, the menu options looks really, really blank. So I'm thinking putting a time trial mode (later on after everything else is perfection, not much left anyways) to the game would make it more engaging and give more content ig?

Also how do I contribute to this project? (Maps etc) and out of curiosity what game engine did you use. (Sorry English isn't my first language).

**Comment by agateau** [comment]
Sorry, but having different modes is not something I am going to dive in: I am trying to wrap this game before I start on a new one.

Regarding contributing a new map, the process is documented in https://github.com/agateau/pixelwheels/blob/master/docs/map-format.md.

The engine is built using libgdx.

**Comment by StandWeird** [comment]
Ah, makes sense! Thanks for the feedback.
