### ISSUE TITLE
Show total championship time in "championship finished" screen (was: Cars with same score should be ex-æquo)

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#42]
When two cars finish a championship with the same score, it would be great to say they’re ex-æquo; by not displaying the number that indicates the classification near the second one, and by changing (when needed) the animation with the planes, so that the cars are at the same level.

**Comment by agateau** [comment]
The game tries hard to avoid ex-aequo: if two racers end up with the same score, it uses the sum of the total times to decide who wins. I think it should stay this way.

**Comment by Obsidien** [comment]
Well, as there’s nowhere displayed the complete time of the championship, that’s not clear for the player. And can make him unhappy if he finish after a car that has the same point numbers than her/him. Can I reopen for “unclarty,” then?

**Comment by agateau** [comment]
You are right, showing the complete time would remove the ambiguity.

**Comment by agateau** [comment]
Here you go!

![image](https://user-images.githubusercontent.com/3575/102187922-ec094d00-3eb4-11eb-9a9c-d01fba0e0524.png)
