### ISSUE TITLE
Championship scores are shown at Quick Race

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#43]
![a screenshot of a regular scoreboard in Quick Race](https://user-images.githubusercontent.com/10854855/64912953-75a7f900-d70d-11e9-870e-4d937f5e6be0.png)

i do not think that is necessary when only one race is involved.

**Comment by BrianGaucher** [comment]
I agree, though no harm is done, the score could be removed for a single race.

**Comment by agateau** [comment]
Agreed.
