### ISSUE TITLE
Possible to build it for Android 4.0?

### ISSUE THREAD

**Issue by khartahk** [agateau/pixelwheels#432]
## Describe the bug

Want to install it on Samsung Galaxy Tab 10.1 with Android 4.0 using ADB, get INSTALL_FAILED_OLDER_SDK error.

### How to reproduce

1. download apk
2. install using `adb install name-of.apk`
3. get error about the older sdk

## Information about your build

Pixel Wheels version: 0.22.0

Binary origin:
- [X] Other: github releases gplay apk

OS:

- [X] Android

OS version: 4.0.4

## Optional information

I have a Samsung Galaxy Tab 10.1 with android 4.0.something. Would it be possible to compile this game for that? 

I'd really like to get this working since the only way to install apps on it is using adb since no website nor app store works with it any more and it was just factory reset-ed by accident.

**Comment by agateau** [comment]
Hi, sorry for the late reply. I try my best to support as many Android versions as possible, but I have to bump minimum versions from time to time. The latest version cannot be rebuilt for Android 4.0.4. I think the newest compatible version would be 0.12.0, but that is quite old :/. You can download it from https://agateau.com/storage/pixelwheels/.
