### ISSUE TITLE
Keyboard mapping config not persisted over restart?

### ISSUE THREAD

**Issue by complyue** [agateau/pixelwheels#440]
## Describe the bug

I changed P1's keyboard key mappings to ASD and played fine. But once the game is restarted, the key mapping is reverted to arrow keys.

### How to reproduce

1. start the game
2. change keyboard mapping to other than default
3. restart the game
4. the key mappings are reverted to default

### Expected behavior

Key mappings should persist over restarts of the game

## Information about your build

Pixel Wheels version:

master branch @ 2.5.1

Binary origin:

- [ ] itch.io
- [ ] Google Play
- [ ] F-Droid
- [ ] <https://builds.agateau.com/pixelwheels/>
- [ x] Self-built
- [ ] Other:

OS:

- [ ] Android
- [ ] Windows
- [ ] macOS
- [x ] Linux

OS version:

## Optional information

I'd like to contribute a PR for a fix, but no idea where to start looking.

## Additional context

N/A

**Comment by agateau** [comment]
Hi,

This is odd: I can't reproduce it. Some more details about this:
- Key bindings are saved to disk by `GameConfig.savePlayerInputHandlerConfig()`
- They are stored in `~/.config/pixelwheels/pixelwheels.conf`
- They are loaded from disk by `GameConfig.setupInputHandlers()` (which is a bit convoluted...)

**Comment by complyue** [comment]
Really odd, it works for me this time, closing.
