### ISSUE TITLE
First car should not always have mines

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#46]
I understand why the first car should usually prefer have mines than other gifts, but I think it should sometimes be allowed to have other ones. Let’s say that probably the booster is not a good idea (it would made best scores more random), but having a rocket or other weapons would be great, when you’re taking a lap to followers.

**Comment by agateau** [comment]
Agreed.

**Comment by Obsidien** [comment]
If I read the MR correctly, it is allowing to have the Turbo bonus when heading the race. I think that is a quite bad idea, as that will make the “total” race scores mostly “unreliable” to know if someone is a good pilot (the “best lap” ranking is already polluted by that, as an easy way to have a best lap is to obtain this bonus, and then to prepare for doing correctly your next lap). I can try a MR, but I don’t know how to test the stuff…

**Comment by Obsidien** [comment]
In fact, I’d even disable that bonus for the second car, because of some levels where the second car can take a bonus and then take the first place.

**Comment by agateau** [comment]
You have a very good point regarding not allowing turbo for the first and second cars. Regarding testing, since it's all probabilities, you would have to either run a lot of races or write unit tests for the BonusPool, or (probably easier) for AgcMathUtils.arrayLerp().

**Comment by Obsidien** [comment]
> Regarding testing, since it's all probabilities, you would have to either run a lot of races or write unit tests for the BonusPool, or (probably easier) for AgcMathUtils.arrayLerp().

I wouldn’t mind playing a lot of races. ^^ But the problem is that I don’t know how to create an Android package from the code, nor did I managed until now to run it on my computer. I’ll try again, maybe.

Should the issue be reopened until completely fixed?

**Comment by agateau** [comment]
Yes, let me reopen it. I can look into it if you're not fluent with Java :)
