### ISSUE TITLE
Let explore the gardens!

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#50]
In Don’t Slip! and Blocky Town, there are fun gardens; it would be great to have a way to explore them! Could fences have an automatic opening that let the gardens look inaccessible, but would allow to explore them if you present your car there?

**Comment by agateau** [comment]
I am not sure why I turned this PR into "Allow movable objects" :thinking:, I just reverted that title change.

I think automated fences are too much work for what they would bring to the game play, so I am not going to add them, sorry.
