### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#57]
I assumed in a previous bug report that there were part of the application translated, but in fact, there aren’t, right? It would be great to have some, at least the one in French. ^^

**Comment by agateau** [comment]
I have been lazy on that one, I need to setup translations!

**Comment by Wilker-a** [comment]
i can help translate to portuguese if it is on Weblate \^\^

**Comment by Porrumentzio** [comment]
Where can the translations be made?

**Comment by agateau** [comment]
It's not possible to translate the game for now: strings are hard-coded to English. I need to integrate translation support.

**Comment by Porrumentzio** [comment]
I'm not a programmer at all, more a translator and sound technician, but I could help making strings translatable.
Gettext is a good option.

**Comment by agateau** [comment]
Yes, I plan to use gettext. Like I did in https://github.com/agateau/burgerparty.

**Comment by My-Creativity** [comment]
Anything changed?

**Comment by agateau** [comment]
Not yet. This will be in 1.1.0. Which might or might not happen, depending on the success of 1.0.0.

**Comment by agateau** [comment]
Pixel Wheels is now translatable! Have a look at https://github.com/agateau/pixelwheels/blob/master/docs/translations.md if you want to translate it.
