### ISSUE TITLE
Rocket over tower

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#58]
In Tiny-sur-Mer, the square tower that is in the sand part looks greatly designed with its shadow, but the rocket bonus is drawn on top of the roof.

**Comment by Obsidien** [comment]
I already reported that there were in Tiny-sur-Mer a fence that was not blocking the cars; I never knew if it was on purpose, but in case it is: it has the same problem, the rocket is drawn over the fence (while the car is drawn under).

**Comment by agateau** [comment]
> the rocket bonus is drawn on top of the roof.

That's a problem indeed :)

> Tiny-sur-Mer a fence that was not blocking the cars; I never knew if it was on purpose, but in case it is: it has the same problem, the rocket is drawn over the fence (while the car is drawn under).

Which fence is it? Can you provide a screenshot?

**Comment by Wilker-a** [comment]
i believe that they mean this one :3
![a screenshot of the fence](https://user-images.githubusercontent.com/10854855/68095233-b6b3c280-fe9f-11e9-8ba9-1552c69645a0.png)

**Comment by Obsidien** [comment]
Yeps, that one. :·) (first reported on #48, §3.) And I don’t know how to do a screenshot on Android. ^^
