### ISSUE TITLE
Vectors for map building

### ISSUE THREAD

**Issue by Wilker-a** [agateau/pixelwheels#69]
i got this idea, but idk if it is good or easy to implement...

what if maps were built using vectors?

i mean as in something close to SVGs and stuff, with shapes for roads, buildings, off-road stuff and symbols/textures.

would that make it easier to create a level creation tool? perhaps make it easier to render or build maps and shadows and stuff?

what do you think?

**Comment by Obsidien** [comment]
I didn’t check how things are done now, but usually, using svg/vector stuff allows better visual results, but for far far *more* work, than just using textured tiles. And for easily doing a level creation tool, tiles are “perfect” (shadows are hard however you do things, as they need the info of the 3rd dimension; but they can be done as a second level of tiles).

**Comment by Wilker-a** [comment]
but as the game is entirely 2d, all you usually need to know would be at least the shape of an object, the layer it is drawn on, the angle of the shadows and the lenght of this shadow.

as for the textures, tiling the textires and masking using the vectors are likely the easiest path, but i guess there should be more looking into the performance and how the visuals would work in limits between one area of the vector and another (limits between different textures)

**Comment by agateau** [comment]
That would need a major rework of the game engine. I am not going to dive into that rabbit hole.

Tracks are created using [Tiled Map Editor](https://www.mapeditor.org/) so it is almost already possible to create custom tracks without writing code. The code change to do is to add the track to the hard-coded track and championship lists. This limitation can be reworked.
