### ISSUE TITLE
New left-turning map

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#74]
In the future map designs, it would be great to include one where cars globally turn left, for varying a bit. One in 8 would be fun also, but that means the car is hidden at one point… not sure how much it would work.

**Comment by Wilker-a** [comment]
additionaly, backtracking should be a thing for races, too.

how about backtracking tie-breakers in championships, too? probably needs some thought about conditions and rules though...

**Comment by Obsidien** [comment]
(For a race in 8, can we have a “glass bridge” that would allow to see what is happening under, while making clear it is not happening over?)

**Comment by agateau** [comment]
Oh, I never noticed all tracks turned right. There is no reason for this indeed. Will take this into account for the next one.

Regarding a track in 8, that is something I definitely want to do, because it opens more track possibilities, but the game engine needs some additional work to support them.

**Comment by Obsidien** [comment]
> Oh, I never noticed all tracks turned right. There is no reason for this indeed. Will take this into account for the next one.

Well, most of the physical circuits turn right, also. But not all ([random link in French on the matter](https://besidesport.com/ces-circuits-de-f1-qui-tournent-a-lenvers/)). So, well, one turning left from time to time would be fun. :·)

**Comment by Knusper** [comment]
A race in 8 with no bridge at all, just a crossing would also be fun

**Comment by Obsidien** [comment]
> A race in 8 with no bridge at all, just a crossing would also be fun

That needs the notion of checkpoint (so that the user does not take the smallest ring), that does not exist for now (first talked on #49 about accelerators).

**Comment by agateau** [comment]
We do have left-turning track now :)
