### ISSUE TITLE
Android: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [agateau/pixelwheels#83]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by agateau** [comment]
Adaptive icons sounds fun, but I'd rather focus on more important topics for now. I would be happy to merge a pull-request implementing it if you are interested in looking into this, though.

**Comment by agateau** [comment]
Right now Pixel Wheels icon is displayed inside a white disc on recent Android versions. I guess this is because it lacks an adaptive icon. I am moving this to 0.22.0 then.
