### ISSUE TITLE
Add more sounds, both to in-game and to pre-game

### ISSUE THREAD

**Issue by Porrumentzio** [agateau/pixelwheels#88]
I could try to create sounds for this and, if you specify where should I add them in the code, I could PR

**Comment by agateau** [comment]
Thanks for offering your help! Do you have examples in mind of sounds to add?

**Comment by Porrumentzio** [comment]
Mostly it is about playing a sound when a button is touched, because otherwise it is confusing sometimes.
A retro music until starting a race also would be good.

Some other in-game sound would be good, I don't remember now but I had ideas.

**Comment by agateau** [comment]
- Music should arrive soon I hope: I asked my brother to compose one for the game.
- A sound when a button is touched is a good idea indeed..

I created issue #91 for the button sound. I am going to close this issue because I prefer to have more focused issues.
