### ISSUE TITLE
We cannot see the lap recorda anymore

### ISSUE THREAD

**Issue by krail16** [agateau/pixelwheels#90]
After the last update I am unnable to see the lap best times when I tap on the track on a quick race. It would be nice if we can see them again.

**Comment by agateau** [comment]
This got lost in 0.16.0 when the new track was added: there was not enough room to fit all the tracks so I removed the lap records.

This is annoying indeed, will look into it, it needs a redesign of the track list, maybe as an horizontally scrolling single-line list :thinking:

**Comment by agateau** [comment]
This has been fixed in current master.
