### ISSUE TITLE
Floating rocks are weird

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#93]
In the level where there’s water, we can see a rock appearing on multiple places. The “multiple places” is a bit problematic, because that makes the pixmap more evident. But the main bug, is that you can go with your car under the rock…

**Comment by agateau** [comment]
Damn, I thought I placed those rocks far enough that one could not reach them!

Will look into this collision issue, and maybe draw a few variants of the tile so that it looks less odd.
