### ISSUE TITLE
Cars should be able to go out the map

### ISSUE THREAD

**Issue by Obsidien** [agateau/pixelwheels#95]
Currently, cars are blocked when trying to go out the map. I think it should be better to let them go out, and then call an helicopter to bring them back.

**Comment by agateau** [comment]
What do you mean with blocked? Most maps are designed so that there is no way to hit the map borders, did you manage to find holes?

**Comment by Obsidien** [comment]
I had specifically in mind the Tiny-sur-Mer map, where you can hit the map border under-water.

**Comment by agateau** [comment]
Oh, you really manage to drive pretty fast under-water! that's impressive :smile: 
This can probably be fixed by adding a few water tile rows and columns to push the boundaries and/or make the water slow down vehicles a bit more aggressively.
